### ISSUE TITLE
chatgpt token limit

### ISSUE THREAD

**Issue by LukeAnger1** [LukeAnger1/search-files-using-gpt4#3]
There is a token limit that is going off. This is causing problems with the sheer number of files or sheer size of file. Going to fix both eventually.

**Comment by LukeAnger1** [comment]
Traceback (most recent call last):
  File "/mnt/c/Users/Luke Anger/Desktop/search-files-using-gpt4/search_files.py", line 67, in <module>
    main()
  File "/mnt/c/Users/Luke Anger/Desktop/search-files-using-gpt4/search_files.py", line 60, in main
    process_directory(path, prompt, output_file)
  File "/mnt/c/Users/Luke Anger/Desktop/search-files-using-gpt4/search_files.py", line 38, in process_directory
    process_file(file_path, prompt, output_file)
  File "/mnt/c/Users/Luke Anger/Desktop/search-files-using-gpt4/search_files.py", line 19, in process_file
    response = gpt.chatgpt(full_prompt)
  File "/mnt/c/Users/Luke Anger/Desktop/search-files-using-gpt4/ask_gpt.py", line 11, in chatgpt
    chat_completion = client.chat.completions.create(
  File "/home/help/.local/lib/python3.10/site-packages/openai/_utils/_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
  File "/home/help/.local/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 663, in create
    return self._post(
  File "/home/help/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1200, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/help/.local/lib/python3.10/site-packages/openai/_base_client.py", line 889, in request
    return self._request(
  File "/home/help/.local/lib/python3.10/site-packages/openai/_base_client.py", line 980, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "This model's maximum context length is 16385 tokens. However, your messages resulted in 18037 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}

**Comment by LukeAnger1** [comment]
It has been fixed. Can now set the max_char token limit. But it doesn't take into account the begining og the prompt and any hidden tokens.
